@VirtualRyan.Server_HostAddress = http://localhost:5074


### A2A API Test
POST {{VirtualRyan.Server_HostAddress}}/api/a2a/ask
Content-Type: application/json
Accept: application/json
{
  "question": "What is your name?"
}
###
