@VirtualRyan.Server_HostAddress = http://localhost:5074

POST {{VirtualRyan.Server_HostAddress}}/chat/AskQuestion/
Content-Type: application/json
Accept: application/json
{
  "question": "What is the meaning of life?"
}
###
